version: '3.8'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_statistics
      - SPRING_DATASOURCE_USER=ewm_statistics
      - SPRING_DATASOURCE_PASSWORD=statistics

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_statistics
      - POSTGRES_USER=ewm_statistics
      - POSTGRES_PASSWORD=statistics

  ewm-service:
    build: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main
      - SPRING_DATASOURCE_USER=ewm_main
      - SPRING_DATASOURCE_PASSWORD=main
      - stats-server.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=ewm_main
      - POSTGRES_PASSWORD=main
